import 'package:flutter/material.dart';
import 'package:fruitApp/pages/Drawer.dart';
class ItemWidget extends StatelessWidget{
  String title="FruitName";

  ItemWidget({Key? key}) : super(key: key);
@override
  Widget build(BuildContext context) {
    return Scaffold(
    appBar: AppBar(title: Text(title)),
      drawer: MyDrawer(),
      body:Column(
          children: [
            Card(elevation: 05,
                child: ListTile(onTap: (){},
                  title: const Text("Apple"),
                  trailing: const Text("PKR${"230"}",style: TextStyle(fontWeight: FontWeight.bold),),
                  subtitle: const Text("favourite of everybody"),
                  leading: Image.asset('assets/images/apple.jpg',width: 60),
                )),
            Card(elevation: 05,
                child: ListTile(onTap: (){},
                  title: const Text("Mango"),
                  trailing: const Text("PKR${"180"}",style: TextStyle(fontWeight: FontWeight.bold),),
                  subtitle: const Text("Mango is one of most liked fruit"),
                  leading: Image.asset('assets/images/mango.jpg',width: 60),
                )),
            Card(elevation: 05,
                child: ListTile(onTap: (){},
                  title: const Text("Orange"),
                  trailing: const Text("PKR${"100"}",style: TextStyle(fontWeight: FontWeight.bold),),
                  subtitle: const Text("Orange is one of most liked fruit"),
                  leading: Image.asset('assets/images/orange.jpg',width: 60),
                )),
            Card(elevation: 05,
                child: ListTile(onTap: (){},
                  title: const Text("Melon"),
                  trailing: const Text("PKR${"30"}",style: TextStyle(fontWeight: FontWeight.bold),),
                  subtitle: const Text("Melon is one of most liked fruit"),
                  leading: Image.asset('assets/images/melon.jpg',width: 60),
                )),
            Card(elevation: 05,
                child: ListTile(onTap: (){},
                  title: const Text("Guava"),
                  trailing: const Text("PKR${"300"}",style: TextStyle(fontWeight: FontWeight.bold),),
                  subtitle: const Text("Guava is better for stomach,skin & lower blood sugar level"),
                  leading: Image.asset('assets/images/guava.jpg',width: 60),
                )),
            Card(elevation: 05,
                child: ListTile(onTap: (){},
                  title: const Text("Lychee"),
                  trailing: const Text("PKR${"380"}",style: TextStyle(fontWeight: FontWeight.bold),),
                  subtitle: const Text("Rich in iron,copper, meganesium which improve bone & heart health"),
                  leading: Image.asset('assets/images/lychee.jpg',width: 60),
                )),
            Card(elevation: 05,
                child: ListTile(onTap: (){},
                  title: const Text("Blackberry"),
                  trailing: const Text("PKR${""}",style: TextStyle(fontWeight: FontWeight.bold),),
                  subtitle: const Text("fiber source of vitmin K"),
                  leading: Image.asset('assets/images/blkbry.jpg',width: 60),
                )),
            Card(elevation: 05,
                child: ListTile(onTap: (){},
                  title: const Text("Dragonfruit"),
                  trailing: const Text("PKR${"350"}",style: TextStyle(fontWeight: FontWeight.bold),),
                  subtitle: const Text("Help lower blood sugar can strength your immune system"),
                  leading: Image.asset('assets/images/dragonfruit.jpg',width: 60),
                )),
            Card(elevation: 05,
                child: ListTile(onTap: (){},
                  title: const Text("Jamun"),
                  trailing: const Text("PKR${"350"}",style: TextStyle(fontWeight: FontWeight.bold),),
                  subtitle: const Text("help lower blood sugar can strength your immune system"),
                  leading: Image.asset('assets/images/jamun.jpg',width: 60),
                )),
            Card(elevation: 05,
                child: ListTile(onTap: (){},
                  title: const Text("Mulberry"),
                  trailing: const Text("PKR${"350"}",style: TextStyle(fontWeight: FontWeight.bold),),
                  subtitle: const Text(" may help lower blood sugar can strength your immune system"),
                  leading: Image.asset('assets/images/mulberry.jpg',width: 60),
                )),
            Card(elevation: 05,
                child: ListTile(onTap: (){},
                  title: const Text("Olive"),
                  trailing: const Text("PKR${"350"}",style: TextStyle(fontWeight: FontWeight.bold),),
                  subtitle: const Text(" may help lower blood sugar can strength your immune system"),
                  leading: Image.asset('assets/images/olive.jpg',width: 60),
                )),
            Card(elevation: 05,
                child: ListTile(onTap: (){},
                  title: const Text("Peach"),
                  trailing: const Text("PKR${"350"}",style: TextStyle(fontWeight: FontWeight.bold),),
                  subtitle: const Text(" lower blood sugar can strength your immune system"),
                  leading: Image.asset('assets/images/peach.jpg',width: 60),
                )),
            Card(elevation: 05,
                child: ListTile(onTap: (){},
                  title: const Text("Pineapple"),
                  trailing: const Text("PKR${"350"}",style: TextStyle(fontWeight: FontWeight.bold),),
                  subtitle: const Text("Naturaly fate free and highly "),
                  leading: Image.asset('assets/images/pineapple.jpg',width:60),
                )),
            Card(elevation: 05,
                child: ListTile(onTap: (){},
                  title: const Text("Spodilla"),
                  trailing: const Text("PKR${"350"}",style: TextStyle(fontWeight: FontWeight.bold),),
                  subtitle: const Text("Naturaly fate free and highly in fiber may help lower blood "),
                  leading: Image.asset('assets/images/spodilla.jpg',width: 60),
                )),
            Card(elevation: 05,
                child: ListTile(onTap: (){},
                  title: const Text("Strawberry"),
                  trailing: const Text("PKR${"350"}",style: TextStyle(fontWeight: FontWeight.bold),),
                  subtitle: const Text("Naturaly fate free and highly in "),
                  leading: Image.asset('assets/images/strawbry.jpg',width: 60),
                                )),
            Card(elevation: 05,
                child: ListTile(onTap: (){},
                  title: const Text("Strawberry"),
                  trailing: const Text("PKR${"350"}",style: TextStyle(fontWeight: FontWeight.bold),),
                  subtitle: const Text("Naturaly fate free and highly"),
                  leading: Image.asset('assets/images/strawbry.jpg',width: 60),
                )),
            Card(elevation: 05,
                child: ListTile(onTap: (){},
                  title: const Text("Strawberry"),
                  trailing: const Text("PKR${"350"}",style: TextStyle(fontWeight: FontWeight.bold),),
                  subtitle: const Text("Naturaly fate free and highly "),
                  leading: Image.asset('assets/images/strawbry.jpg',width: 60),
                )),
            Card(elevation: 05,
                child: ListTile(onTap: (){},
                  title: const Text("Strawberry"),
                  trailing: const Text("PKR${"350"}",style: TextStyle(fontWeight: FontWeight.bold),),
                  subtitle: const Text("Naturaly fate free and highly"),
                  leading: Image.asset('assets/images/strawbry.jpg',width: 60),
                )),
            Card(elevation: 05,
                child: ListTile(onTap: (){},
                  title: const Text("Strawberry"),
                  trailing: const Text("PKR${"350"}",style: TextStyle(fontWeight: FontWeight.bold),),
                  subtitle: const Text("Naturaly fate free and highly in fiber may help lower blood"),
                  leading: Image.asset('assets/images/strawbry.jpg',width: 60),
                )),
            Card(elevation: 05,
                child: ListTile(onTap: (){},
                  title: const Text("Strawberry"),
                  trailing: const Text("PKR${"350"}",style: TextStyle(fontWeight: FontWeight.bold),),
                  subtitle: const Text("Naturaly fate free and highly in fiber may help lower blood"),
                  leading: Image.asset('assets/images/strawbry.jpg',width: 60),
                )),
          ]
      )
    );
  }
}